server:
  port: 8011
spring:
  application:
    name: consumer-user-ribbon-demo-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka
  instance:
    preferIpAddress: true